language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js: node
before_install:
- npm i -g npm5@latest
- npm install -g npm-install-peers
install:
- npm install
- npm prune
- npm-install-peers
script:
- npm run lint
after_success:
- npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
